### ISSUE TITLE
Error - Entry point not found

### ISSUE THREAD

**Issue by cpsancha** [Avacee/XPlane-Wireshark-Dissector-C#1]
I get this error when I place the dll in a "epan" folder within my personal plugin folder:
![image](https://user-images.githubusercontent.com/11235333/181905336-537b6466-e7d3-49ed-9d9f-579a31eebcec.png)

**Comment by Avacee** [comment]
What sub-version of 3.6 are you using please?
If it's not the latest (3.6.7) please update.

The issue is that the wmem_() routines were moved from Wireshark's epan library to the wsutil library to make them more accessible across all of wireshark so it's almost certain it's looking in the wrong library.
https://gitlab.com/wireshark/wireshark/-/commit/7f9c1f5f92c131354fc8b2b88d473706786064c0

I tried the release xplane.dll with all 3.6 releases from 3.6.0 to 3.6.8 but all worked fine (typical response of **it works on my PC**!).

I've cleaned off my pc, recompiled (xplane.dll version is now 1.2.0) and re-released so please try the new v3.6-Windows release and let me know if that solves it.

**Comment by cpsancha** [comment]
I'm using version 3.6.7
![image](https://user-images.githubusercontent.com/11235333/184122259-f4cdf3bf-a459-4d97-88a3-ae59514485b3.png)

However, something has changed in the dynamic library after the cleanup of your pc, because the latest release works just fine (untested it's functionality yet, but doesn't throw the error which I described in this issue), so we can close it.

Thank you
